name: Build and Release

on:
  push:
    tags:
      - "v*"  # Runs on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Adjust version if needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile collectUncertainties.py

      - name: Upload Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: collectUncertainties.exe
          path: dist/collectUncertainties.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Built Executable
        uses: actions/download-artifact@v4
        with:
          name: collectUncertainties.exe
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/collectUncertainties.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
